/**
 * Writes apps/api/wrangler.production.jsonc from apps/api/wrangler.jsonc plus deploy-time settings
 * (GitHub Actions variables). Nothing environment-specific is committed.
 *
 *   D1_DATABASE_ID=… node scripts/prod-config.mjs
 *   Optional: SITE_URL, CUSTOM_DOMAIN
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** JSON with // comments (as wrangler.jsonc uses). Comments inside strings are kept. */
export function parseJsonc(text) {
  let out = "";
  let inString = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      out += ch;
      if (ch === "\\") out += text[++i] ?? "";
      else if (ch === '"') inString = false;
    } else if (ch === '"') {
      inString = true;
      out += ch;
    } else if (ch === "/" && text[i + 1] === "/") {
      while (i < text.length && text[i] !== "\n") i++;
      out += "\n";
    } else {
      out += ch;
    }
  }
  return JSON.parse(out);
}

export function buildProductionConfig(base, env) {
  if (!env.D1_DATABASE_ID) throw new Error("D1_DATABASE_ID is required (set it as a GitHub Actions variable)");
  const siteUrl = env.SITE_URL || (env.CUSTOM_DOMAIN ? `https://${env.CUSTOM_DOMAIN}` : "");
  if (!siteUrl) throw new Error("SITE_URL or CUSTOM_DOMAIN is required: session cookies are Secure only on https");
  if (!siteUrl.startsWith("https://")) throw new Error("SITE_URL must be https:// in production");
  const config = structuredClone(base);
  config.d1_databases = config.d1_databases.map((d) => (d.binding === "DB" ? { ...d, database_id: env.D1_DATABASE_ID } : d));
  config.assets = {
    directory: "../web/out",
    binding: "ASSETS",
    // Only the API runs the Worker; pages are served straight from assets (free, unmetered).
    run_worker_first: ["/api/*"],
    not_found_handling: "404-page",
    html_handling: "auto-trailing-slash",
  };
  config.vars = { ...config.vars, ENVIRONMENT: "production", LOG_LEVEL: "info", SITE_URL: siteUrl };
  // 30 sign-in attempts per IP per minute: a class signing in together from one school network still gets through.
  config.ratelimits = (config.ratelimits ?? []).map((r) => (r.name === "LOGIN_LIMITER" ? { ...r, simple: { limit: 30, period: 60 } } : r));
  config.workers_dev = true;
  if (env.CUSTOM_DOMAIN) config.routes = [{ pattern: env.CUSTOM_DOMAIN, custom_domain: true }];
  return config;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const apiDir = resolve(dirname(fileURLToPath(import.meta.url)), "../apps/api");
  const base = parseJsonc(readFileSync(resolve(apiDir, "wrangler.jsonc"), "utf8"));
  const config = buildProductionConfig(base, process.env);
  const out = resolve(apiDir, "wrangler.production.jsonc");
  writeFileSync(out, "// Generated by scripts/prod-config.mjs. Do not edit or commit.\n" + JSON.stringify(config, null, 2) + "\n");
  console.log(`wrote ${out} (site: ${config.vars.SITE_URL}, custom domain: ${config.routes ? config.routes.map((r) => r.pattern).join(", ") : "none, workers.dev only"})`);
}
